use_frameworks!

target 'GKFadeNavigationController_Example' do
    pod 'GKFadeNavigationController', :path => '../'
    
    target 'GKFadeNavigationController_Tests' do
        inherit! :search_paths
        
        
    end
end
