source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GKFadeNavigationController_Example', :exclusive => true do
  pod "GKFadeNavigationController", :path => "../"
end

target 'GKFadeNavigationController_Tests', :exclusive => true do
  pod "GKFadeNavigationController", :path => "../"

  
end
